"""Idempotency helpers for Alembic migrations.

Several migrations in this project were autogenerated against a database
whose tables/columns had already been created out-of-band (e.g. via
``Base.metadata.create_all()`` during local development), rather than by
running the migration chain from scratch. As a result, running
``alembic upgrade head`` against a genuinely empty database (CI, a fresh
environment) fails with "relation/column does not exist" or, once the
initial migration bootstraps the schema via ``create_all()``, with
"column already exists" in the migrations that follow.

These helpers let each migration check whether its target table/column/
index already exists before trying to create it, so the same migration
chain works correctly both for a fresh database and for an existing
production database that is missing exactly the objects each migration
was written to add.
"""
from __future__ import annotations

import sqlalchemy as sa


def table_exists(bind: sa.engine.Connection, table_name: str) -> bool:
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(bind: sa.engine.Connection, table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(bind)
    if table_name not in inspector.get_table_names():
        return False
    return any(col["name"] == column_name for col in inspector.get_columns(table_name))


def index_exists(bind: sa.engine.Connection, table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(bind)
    if table_name not in inspector.get_table_names():
        return False
    return any(idx["name"] == index_name for idx in inspector.get_indexes(table_name))
