"""add_raw_source_text_to_orders

Revision ID: 07ea26748075
Revises: 282aea5e6f46
Create Date: 2026-06-27 16:22:26.377557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.utils.migration_helpers import column_exists


# revision identifiers, used by Alembic.
revision: str = '07ea26748075'
down_revision: Union[str, Sequence[str], None] = '282aea5e6f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if not column_exists(bind, 'orders', 'raw_source_text'):
        with op.batch_alter_table('orders', schema=None) as batch_op:
            batch_op.add_column(sa.Column('raw_source_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('raw_source_text')

    # ### end Alembic commands ###
