"""make_product_id_nullable_and_add_unmatched_raw_text

Revision ID: 282aea5e6f46
Revises: 0a4560241e1f
Create Date: 2026-06-27 13:28:48.034874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.utils.migration_helpers import column_exists


# revision identifiers, used by Alembic.
revision: str = '282aea5e6f46'
down_revision: Union[str, Sequence[str], None] = '0a4560241e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    with op.batch_alter_table('order_line_items', schema=None) as batch_op:
        if not column_exists(bind, 'order_line_items', 'unmatched_raw_text'):
            batch_op.add_column(sa.Column('unmatched_raw_text', sa.String(length=255), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.CHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.CHAR(length=36),
               nullable=False)
        batch_op.drop_column('unmatched_raw_text')

    # ### end Alembic commands ###
