"""add_razorpay_tenant_columns

Revision ID: 80d9a0a31875
Revises: d4e5f6a7b8c9
Create Date: 2026-07-04 22:38:58.167967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.utils.migration_helpers import column_exists


# revision identifiers, used by Alembic.
revision: str = '80d9a0a31875'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    with op.batch_alter_table('distributor_tenants', schema=None) as batch_op:
        if not column_exists(bind, 'distributor_tenants', 'razorpay_key_id'):
            batch_op.add_column(sa.Column('razorpay_key_id', sa.String(length=100), nullable=True))
        if not column_exists(bind, 'distributor_tenants', 'razorpay_key_secret_enc'):
            batch_op.add_column(sa.Column('razorpay_key_secret_enc', sa.String(length=500), nullable=True))
        if not column_exists(bind, 'distributor_tenants', 'razorpay_account_name'):
            batch_op.add_column(sa.Column('razorpay_account_name', sa.String(length=200), nullable=True))
        if not column_exists(bind, 'distributor_tenants', 'razorpay_mode'):
            batch_op.add_column(sa.Column('razorpay_mode', sa.String(length=10), nullable=False, server_default='test'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributor_tenants', schema=None) as batch_op:
        batch_op.drop_column('razorpay_mode')
        batch_op.drop_column('razorpay_account_name')
        batch_op.drop_column('razorpay_key_secret_enc')
        batch_op.drop_column('razorpay_key_id')

    # ### end Alembic commands ###
