"""add_whatsapp_connection_status_columns

Revision ID: 9220f29d683d
Revises: f1a2b3c4d5e6
Create Date: 2026-07-06 20:22:11.220977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9220f29d683d'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_gaps', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('distributor_tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_connection_status', sa.String(length=20), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('whatsapp_disconnected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_disconnect_reason', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributor_tenants', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_disconnect_reason')
        batch_op.drop_column('whatsapp_disconnected_at')
        batch_op.drop_column('whatsapp_connection_status')

    with op.batch_alter_table('demand_gaps', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
