"""add_whatsapp_connection_status_columns

Revision ID: 9220f29d683d
Revises: f1a2b3c4d5e6
Create Date: 2026-07-06 20:22:11.220977

"""
from typing import Sequence, Union
import logging

from alembic import op
import sqlalchemy as sa

from app.utils.migration_helpers import column_exists, table_exists

logger = logging.getLogger(__name__)


def _demand_gaps_columns_are_uuid(bind) -> bool:
    """True if demand_gaps.id is currently a UUID column.

    demand_gaps is created directly with real UUID columns by the merge
    migration c1a2b3d4e5f6, which always runs before this one in the
    actual (merged) revision chain -- so by the time this migration's
    upgrade() runs, the NUMERIC-typed state the alter_column calls below
    assume can never genuinely occur here anymore. That makes the
    NUMERIC->UUID conversion a no-op on upgrade, but its mirror-image
    UUID->NUMERIC conversion in downgrade() is not a no-op: Postgres has
    no automatic cast from uuid to numeric, so it unconditionally raised
    (see DB-4) regardless of row count or any existence guard. Guarding
    both directions on the columns' *actual current type* (only convert
    when a real NUMERIC<->UUID mismatch exists) makes this migration
    idempotent and its downgrade actually able to run to completion.
    """
    if not table_exists(bind, 'demand_gaps'):
        return False
    inspector = sa.inspect(bind)
    columns = {c["name"]: c["type"] for c in inspector.get_columns('demand_gaps')}
    id_col = columns.get('id')
    return id_col is not None and 'UUID' in str(id_col).upper()


# revision identifiers, used by Alembic.
revision: str = '9220f29d683d'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    if not _demand_gaps_columns_are_uuid(bind):
        with op.batch_alter_table('demand_gaps', schema=None) as batch_op:
            batch_op.alter_column('id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
            batch_op.alter_column('order_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)
            batch_op.alter_column('customer_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
            batch_op.alter_column('product_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=True)

    # On a genuinely fresh database, the initial-schema migration's fast path
    # (Base.metadata.create_all()) already creates these columns since the
    # current ORM model includes them — guard each add_column so this
    # migration is idempotent both there and on existing databases that are
    # missing exactly these columns.
    with op.batch_alter_table('distributor_tenants', schema=None) as batch_op:
        if not column_exists(bind, 'distributor_tenants', 'whatsapp_connection_status'):
            batch_op.add_column(sa.Column('whatsapp_connection_status', sa.String(length=20), server_default='unknown', nullable=False))
        if not column_exists(bind, 'distributor_tenants', 'whatsapp_disconnected_at'):
            batch_op.add_column(sa.Column('whatsapp_disconnected_at', sa.DateTime(), nullable=True))
        if not column_exists(bind, 'distributor_tenants', 'whatsapp_disconnect_reason'):
            batch_op.add_column(sa.Column('whatsapp_disconnect_reason', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    with op.batch_alter_table('distributor_tenants', schema=None) as batch_op:
        if column_exists(bind, 'distributor_tenants', 'whatsapp_disconnect_reason'):
            batch_op.drop_column('whatsapp_disconnect_reason')
        if column_exists(bind, 'distributor_tenants', 'whatsapp_disconnected_at'):
            batch_op.drop_column('whatsapp_disconnected_at')
        if column_exists(bind, 'distributor_tenants', 'whatsapp_connection_status'):
            batch_op.drop_column('whatsapp_connection_status')

    if _demand_gaps_columns_are_uuid(bind):
        # Postgres has no automatic (or even sensible manual) cast from
        # uuid back to numeric -- a UUID's bit pattern doesn't correspond
        # to any meaningful numeric value. Since demand_gaps.id/order_id/
        # customer_id/product_id are created as real UUID columns by
        # c1a2b3d4e5f6 (which always runs earlier in the merged chain than
        # this migration), the NUMERIC state this block would be
        # "reverting to" never actually existed in this history to begin
        # with -- attempting it unconditionally always raised
        # DatatypeMismatch and made this migration's downgrade impossible
        # to run at all (see DB-4). Skip with a warning instead of
        # crashing; there is nothing genuine to revert here.
        logger.warning(
            "Skipping demand_gaps id/order_id/customer_id/product_id "
            "UUID->NUMERIC downgrade: no valid Postgres cast exists, and "
            "these columns were never actually NUMERIC in this migration "
            "history (see 9220f29d683d)."
        )

    # ### end Alembic commands ###
