"""Initial schema

Revision ID: 9eb6a140e6af
Revises: 
Create Date: 2026-06-20 14:50:20.175083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb6a140e6af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_aliases', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('customer_aliases', 'customer_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('customer_aliases', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('customer_ledgers', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('customer_ledgers', 'customer_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('customer_ledgers', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.add_column('customers', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.alter_column('customers', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('customers', 'credit_limit',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('(100000.0)'))
    op.alter_column('customers', 'outstanding_balance',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.add_column('distributor_tenants', sa.Column('whatsapp_order_phone', sa.String(length=50), nullable=True))
    op.add_column('distributor_tenants', sa.Column('plan_type', sa.String(length=50), nullable=False))
    op.add_column('distributor_tenants', sa.Column('monthly_order_count', sa.Integer(), nullable=False))
    op.alter_column('distributor_tenants', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('ingestion_staging', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('ingestion_staging', 'job_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('ingestion_staging', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('inventory', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('inventory', 'sku_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('inventory', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('invoices', 'order_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=True)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_line_items', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('order_line_items', 'order_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('order_line_items', 'product_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('order_line_items', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('order_state_ledger', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('order_state_ledger', 'order_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('order_state_ledger', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.drop_column('orders', 'payment_status')
    op.alter_column('payment_invoice_links', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('payment_invoice_links', 'payment_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('payment_invoice_links', 'invoice_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('payment_invoice_links', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('payments', 'customer_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_aliases', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_aliases', 'product_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_aliases', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_prices', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_prices', 'product_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_prices', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'product_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'supplier_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(100)'))
    op.alter_column('products', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('shipments', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('shipments', 'order_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('shipments', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.drop_column('shipments', 'payment_status')
    op.add_column('users', sa.Column('email_or_phone', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_unique_constraint(None, 'users', ['email_or_phone'])
    op.alter_column('whatsapp_verifications', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.SafeUUID(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_verifications', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('users', 'firebase_uid')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email_or_phone')
    op.add_column('shipments', sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'UNPAID'"), nullable=False))
    op.alter_column('shipments', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('shipments', 'order_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('shipments', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('products', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(100)'))
    op.alter_column('products', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'supplier_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'product_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_supplier_mappings', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_prices', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_prices', 'product_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_prices', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_aliases', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_aliases', 'product_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('product_aliases', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payments', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payments', 'customer_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payment_invoice_links', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payment_invoice_links', 'invoice_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payment_invoice_links', 'payment_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('payment_invoice_links', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.add_column('orders', sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'UNPAID'"), nullable=False))
    op.alter_column('orders', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('order_state_ledger', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('order_state_ledger', 'order_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('order_state_ledger', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('order_line_items', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('order_line_items', 'product_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('order_line_items', 'order_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('order_line_items', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'])
    op.alter_column('invoices', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('invoices', 'customer_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('invoices', 'order_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('inventory', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('inventory', 'sku_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('inventory', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('ingestion_staging', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('ingestion_staging', 'job_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('ingestion_staging', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('distributor_tenants', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('distributor_tenants', 'monthly_order_count')
    op.drop_column('distributor_tenants', 'plan_type')
    op.drop_column('distributor_tenants', 'whatsapp_order_phone')
    op.alter_column('customers', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('customers', 'outstanding_balance',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('customers', 'credit_limit',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('(100000.0)'))
    op.alter_column('customers', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('customers', 'phone_number')
    op.alter_column('customer_ledgers', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('customer_ledgers', 'customer_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('customer_ledgers', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('customer_aliases', 'tenant_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('customer_aliases', 'customer_id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('customer_aliases', 'id',
               existing_type=app.database.SafeUUID(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
